title: Charlotte Wang
logo: /assets/img/headshot.png
description: Hi I'm Charlotte, I am pursuing a Masterâ€™s Degree in Business Analytics at the University of Utah.

I currently work in Proposal Operations as a Hardware Cost Estimator at L3Harris Technologies.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
